### ISSUE TITLE
select target for nested source

### ISSUE THREAD

**Issue by ghost** [geosolutions-it/hale-appschema-plugin#1]
Hi,

I try to export my alignement following this tutorial https://geoserver.geo-solutions.it/edu/en/complex_features/landcover/lcv_upload.html#hale-lcv-upload.

I try with app-schema configuration but when I have to configure feature chaining and select the nested type’s target, I click on the property in the schema explorer view but nothing happens.

Any reason for this issue?

**Comment by nmco** [comment]
Strange issue, a few UI problems have been recently fixed maybe that was one of them. That say, when reporting an UI issue the ideal si to perform a small video showing the problem, or provide some print screens,

I'm closing this one for now, feel free to reopen if needed.
