### ISSUE TITLE
hale alignment export Cannot find a DataAccess for parameters

### ISSUE THREAD

**Issue by gannebamm** [geosolutions-it/hale-appschema-plugin#24]
Hi Geoserver Users,

I am unable to use a datastore with AppSchema. The log message is:
24 Sep 09:45:00 ERROR [data.resource] - Grabbing the attribute list failed
org.geotools.data.DataSourceException: **Cannot find a DataAccess for parameters** (some not shown) {dbtype=postgis, host=134.xxx.xxx.xxx, database=xxxx, schema=xxxx, user=xxx}

I double checked the same connection parameters as simple postgis datastore do work fine. The database log does not show any errors.

gitter: [23. September 2020 10:57](https://gitter.im/geoserver/geoserver?at=5f6b0ded4002c640b5dff713)
sourceforge Mailing List: https://sourceforge.net/p/geoserver/mailman/message/25820257/

Does anyone have a clue whats wrong here? If needed I could provide appschema files and configuration xmls.
yours,
Florian

**Comment by mpleic** [comment]
You have to specify a port along with a host in the App-Schema DataStore configuration window (e.g. localhost:5432). Form title "Host(:Port)" is confusing in this case, meaning port to be default or optional. But it doesn't actually exports postgresql default port if not specified.

**Comment by nmco** [comment]
Assuming that the answer from @mpleic was enough.
